title:        Futurelink Docs
tagline:      'Все, что не хочется запоминать'
description:  'Здесь лежит все, что не надо запоминать, а надо просто записать. Программизм, микроконтроллеры STM32 и AVR, разработка на Java и прочее'
url:          http://futurelink.ru
version:      1.0
author:
  name:       'Денис Павлов'
  email:      'me@futurelink.ru'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
